### ISSUE TITLE
Smaller p71 gun(?)

### ISSUE THREAD

**Issue by ghost** [ceebo/glider_guns#1]
If this is valid, please update the collection. I can't imagine I'm the first to have found this
(dinosaur Herschel loop built from standard parts, Bx202 + Fx153).
[code]
x = 122, y = 49, rule = LifeHistory
69.2A14.A$44.2A24.A14.3A$29.A15.A13.2A6.3A18.A$27.3A15.A.AB9.B2A2B4.A
19.2A$9.2A15.A19.2AB.3B6.4B.3B20.4B$8.A2BA14.2A20.7B2.7B3AB7.4B2AB.B
5.3B19.A$8.2B2A15.B20.15BA2B2A2B.B3.2AB4A6B.A3B16.3A$4.B2.2B2A2B14.3B
19.13BABABABA6B4AB5A3BA11B8.A9.A$3.2AB.2B2A2B13.6B16.14BA5B2A5BA2BA3B
2A4BA3B2A7B7.2A6.3A$3.2A3B3A4B.B8.10B11.16B9A12BA2BA2BA3BA7B2.B.5B5.A
$4.2B.2B2A7B3.2B2.11B3.2B2.20BA19B5A3BABA7B.6B7.2A$7.13B2A7B2A15B2A
12BA4BA10B3A2B3A2B2A3B2A16B4.4B2.2A$8.12BABA6B2A14B2AB2A3B.5BABA14B2A
3B2AB3.2B2.21B2AB4.A$8.2A12BA22B2AB2A3B2.10BABA3B2.10B11.16BA2BAB.BA.
A$8.12BABA24B3A3B2.7B.3BA7.6B16.13BA3BAB.B2A$7.12B3A30B4.6B2.2B9.3B
19.11B2ABA5B$5.B.9BAB2A2.B4.13B.4B11.6B13.B21.12BA3BA3B$4.2AB.6BA4BA
7.7B.B5.3B13.3B14.2A19.8B2.5B3A5B$4.2A7B2A3BAB19.4B12.7B12.A20.2A3.B
5.5BA6B.BA$5.2B.4BA4BAB20.2A14.2A.B.2A13.3A18.A7.15BA.A$A7.5BAB2A2B
21.A15.A3.A16.A15.3A8.2A3.8B.2BA$3A5.6BA3B19.3A13.3A5.3A29.A11.A2.10B
.B$3.A4.6B23.A15.A9.A38.3A4.10B$2.2A4.7B87.A6.11B$2.12B95.12B$4.10B6.
A87.7B3.3BA$4.10B4.3A38.A9.A15.A23.6B4.ABA$3.B.10B2.A11.A29.3A5.3A13.
3A19.3BA6B5.2A$2.A2B.8B3.2A8.3A15.A16.A3.A15.A21.2B2ABA5B$.A.A15B7.A
18.3A13.2A.B.2A14.2A20.BA4BA4B.2B$2.AB.6BA5B5.B3.2A20.A12.7B12.4B19.B
A3B2A7B2A$5.5B3A5B2.8B19.2A14.3B13.3B5.B.7B7.A4BA6B.B2A$6.3BA3BA12B
21.B13.6B11.4B.13B4.B2.2ABA9B.B$6.5BAB2A11B19.3B9.2B2.6B4.30B3A12B$4.
2AB.BA3BA13B16.6B7.A3B.7B2.3B3A24BABA12B$3.A.AB.BA2BA16B11.10B2.3BABA
10B2.3B2AB2A22BA12B2A$3.A4.B2A21B2.2B3.B2A3B2A14BABA5B.3B2AB2A14B2A6B
ABA12B$2.2A2.4B4.16B2A3B2A2B3A2B3A10BA4BA12B2A15B2A7B2A13B$6.2A7.6B.
7BABA3B5A19BA20B2.2B3.11B2.2B3.7B2A2B.2B$7.A5.5B.B2.7BA3BA2BA2BA12B9A
16B11.10B8.B.4B3A3B2A$4.3A6.2A7.7B2A3BA4B2A3BA2BA5B2A5BA14B16.6B13.2B
2A2B.B2A$4.A9.A8.11BA3B5AB4A6BABABABA13B19.3B14.2B2A2B2.B$11.3A16.3BA
.6B4AB2A3.B.2B2A2BA15B20.B15.2A2B$11.A19.3B5.B.B2A4B7.B3A7B2.7B20.2A
14.A2BA$32.4B20.3B.4B6.3B.B2A19.A15.2A$34.2A19.A4.2B2AB9.BA.A15.3A$
34.A18.3A6.2A13.A15.A$35.3A14.A24.2A$37.A14.2A!
[/code]

**Comment by ceebo** [comment]
Well done. Record breaking guns with Herschel loops are quite rare these days. I will add it before long.

**Comment by ceebo** [comment]
Added. Thanks.
