### ISSUE TITLE
Smaller p49, p53 and p62

### ISSUE THREAD

**Issue by ghost** [ceebo/glider_guns#10]
49 is the minimum period with this inserter (found in p00519osc3.rle and other
variable guns), which can also reduce the p53 and p62.
[code]
x = 159, y = 54, rule = LifeHistory
19.2A11.A$18.B2AB9.A.A$19.3B9.A.A2.2A3.A$18.B.B9.2A.2A2.A2.A.A62.2A
11.A30.B3.B$18.5B8.B2.A.A3.A.A12.2A47.B2AB9.A.A28.7B$18.6B6.2ABA2.4A.
A13.A49.3B9.A.A2.2A3.A17.2B.3A4B.2B$18.8B4.2A.A.A3.A12.BA.A48.B.B9.2A
.2A2.A2.A.A12.A2.2A2BA2BA5B2A$19.13B2.A.AB2.A9.B.B2A49.B3AB8.B2.A.A3.
A.A10.3A2.2AB.2AB2A2B.B2A$17.13B5.A.A2B.A7.4B51.BABA2B6.2ABA2.4A.A10.
A6.B.3BABA3B.B$16.15B5.A2B.2A7.4B51.BABA4B4.2A.A.A3.A12.2A8.3B.3B$16.
15B4.3B10.5B52.4BA8B2.A.AB2.A9.4B$15.17B.B.2B11.6B7.2A40.BA2B3ABA4B5.
A.A2B.A7.3B10.3B.3B$15.14B4A11B2.8B8.A14.2A23.BAB2A4B2A4B5.A2B.2A7.4B
6.B.3BABA3B.B$14.15BA2B2A21B7.A.AB11.2A23.A8B3A3B4.3B10.5B5.2AB.2AB2A
2B.B2A$13.17BA2B2A19B9.2AB.B.3B29.2BAB2AB2A8B.B.2B11.2BA3B4.2A2BA2BA
5B2A$12.2AB3.12BA2BA11B.7B12.7B3.4A22.2BA6BA19B2.3B3A2B5.2B.3A4B.2B$
11.A2.A4.12B2A21B11.7B2.A3.A21.BA2B2A3BA25BAB2A2B7.7B$10.A.2A5.6B3.B
2.2B2.19B11.7B.2BAB22.6BA3BA24BA2BA2B9.B3.B$10.A7.6B14.17B8.10BABAB
21.2AB3.27B.3B2A2B14.2B$9.2A6.9B14.15B.2B2.3BABA7B2A2B20.A2.A4.30BA4B
12.4B$16.A3B4.2A15.21BA3BA9B.2A.2A14.A.2A5.6B3.B2.2B2.19B11.7B$15.B2A
B5.A16.8B.12BA4BA6B4.A.2A14.A7.6B14.17B8.10B$14.BABA7.3A7.2A2.8B3.2B
2A8BA4BA4B6.A16.2A6.9B14.15B.2B2.13B$13.4B10.A7.2A2.2A3.B5.2B2A9BA3BA
4B5.2A23.4B4.2A15.11B2A18B$12.4B24.A10.12BA2BA6B4.A10.A12.4B5.A16.8B.
3BA16B$11.4B.3B.B12.7A12.B.3B.4B8.4B4.3A5.3A11.4B7.3A7.2A2.8B3.B3A16B
$4.18B10.A24.4B10.4B6.A3.A13.4B10.A7.2A2.2A3.B5.20B$3.16B2A2B5.B3.2A
2.2A7.A10.4B12.4B4.2A.B.2A11.4B24.A10.18B$3.16B2A2B3.3BA4B2.2A7.3A7.
4B14.4B3.7B10.4B.3B.B12.7A12.B.3B.4B$3.20B.6BAB16.A5.4B16.4B4.3B5.18B
10.A24.4B$.22B3A3B2AB15.2A4.4B18.4B2.5B3.16B2A2B5.B3.2A2.2A7.A10.4B$
13B2.2B.4B5A6B14.B3A5B6.2A12.4B.6B2.16B2A2B3.8B2.2A7.3A7.4B$10B8.3BA
3BAB2A6B14.3A3B7.A8.2A4.11B.5B2A13B.8B16.A5.4B$.7B11.3B3A3BA9B2.2B2.B
3.2A2BAB5.2A.A9.A5.15B3A22B15.2A4.4B$3.4B12.4BA24BAB3AB4.A2.A10.A.AB
3.10B2A4BA3B2.2B.15B14.5BA3B6.2A$4.2B14.5BAB.20B2ABAB2A3.B2A12.2AB2.
11BA2B2A2B8.17B14.3BABA7.A$5.B3.B9.6BA10BA15BA2BA4B15.15B2A2B11.19B2.
2B2.B3.4B2A5.2A.A$4.5BAB7.19BA13B6A2B16.BA14BAB12.17B2A16B4.A2.A$.2B.
4B3A.2B5.8B2.6B3A14BA2BA2B17.ABA16B12.7B.5B2AB3A16B3.B2A$2A4B2A3BAB2A
4.6B11.2B.B.7B2ABAB2A3B18.2A8BA7B11.13B3AB2A6B2A14B$2AB.2BA2B2A.B2A5.
5B10.3B4.6BAB3A4B19.3B.7B2A3B.B2A8.15B2AB3A5B2A13B$.B.3BAB2A2B.B6.4B
7.2A.2BA5.6B2A2BA4B24.5B2A2B3.BA.A8.8B2.8B2A19B$4.3B.3B10.3B7.A.2BA.A
5.6B3A4B25.4B2.4B5.A8.6B11.2B.B.17B$19.4B9.A2.BA.A2.9BA3B26.3B5.4B4.
2A8.5B10.3B4.15B$4.3B.3B8.2A12.A3.A.A.2A4.8B25.2AB6.4B13.4B7.2A.2BA5.
15B$.B.3BAB2A2B.B6.A10.A.4A2.AB2A6.6B24.A.AB7.4B12.4B7.A.2BA.A5.13B$
2AB.2BA2B2A.B2A2.3A10.A.A3.A.A2.B8.5B24.2AB9.4B9.2AB.B9.A2.BA.A2.13B$
2A4B2A3BAB2A2.A12.A.A2.A2.2A.2A9.B.B25.4B8.4B7.A.AB12.A3.A.A.2A4.8B$.
2B.4B3A.2B17.A3.2A2.A.A9.3B28.2A9.4B6.A13.A.4A2.AB2A6.6B$4.5BAB28.A.A
9.B2AB27.A11.4B4.2A12.A.A3.A.A2.B8.5B$5.B3.B30.A11.2A29.3A9.4B17.A.A
2.A2.2A.2A9.B.B$85.A10.3BA17.A3.2A2.A.A9.3B$97.3BA24.A.A9.B2AB$98.3AB
24.A11.2A!
[/code]

p53:
[code]
x = 173, y = 56, rule = LifeHistory
25.2A11.A79.2A11.A$24.B2AB9.A.A77.B2AB9.A.A$25.3B9.A.A2.2A3.A70.3B9.A
.A2.2A3.A$24.B.B9.2A.2A2.A2.A.A68.B.B9.2A.2A2.A2.A.A$24.5B8.B2.A.A3.A
.A12.2A54.5B8.B2.A.A3.A.A12.2A$24.6B6.2ABA2.4A.A13.A55.6B6.2ABA2.4A.A
13.A$24.8B4.2A.A.A3.A12.BA.A55.8B4.2A.A.A3.A12.BA.A$25.13B2.A.AB2.A9.
B.B2A57.13B2.A.AB2.A9.B.B2A$23.13B5.A.A2B.A7.4B57.13B5.A.A2B.A7.4B$
22.15B5.A2B.2A7.4B56.15B5.A2B.2A7.4B$22.8B2A5B4.3B10.5B56.15B4.3B10.
5B14.2A$21.9B2A6B.B.2B11.6B7.2A45.6B3A8B.B.BA11.6B12.B2A2B$21.13B2A
14B2.8B8.A14.2A29.5BA2BA11B2A7B2.8B13.4B$20.13BA2BA24B7.A.AB11.2A28.
5BA15BABA17B13.4B$19.15B2A24B9.2AB.B.3B34.7BA2BA30B13.4B$18.2AB3.10BA
16B.7B12.7B3.4A26.2AB3.3B3A21B.2BA4B13.7B$17.A2.A4.35B11.7B2.A3.A25.A
2.A4.30B2A3B12.7B$16.A.2A5.6B3.B2.2B2.19B11.7B.2BAB26.A.2A5.6B3.B2.2B
2.9B2A2B3A3B11.7B2A$16.A7.6B14.17B8.10BABAB26.A7.6B14.6B2A5BA3B8.9B2A
$15.2A6.9B14.15B.2B2.13B2A2B25.2A6.9B14.3B3A4BA4B.2B2.11B.B$22.4B4.2A
15.23BA11B.2A30.4B4.2A15.B2A2BA3BA19B$21.4B5.A16.8B.12B2ABA8B4.A29.4B
5.A16.BA5BA.20B$20.4B7.3A11.8B3.2B2A9BAB2A5B6.A.A26.4B7.3A11.8B3.2B2A
16B$19.4B10.A11.2A3.B5.2B2A11BA6B7.2A25.4B10.A11.2A3.B5.2B2A16B$18.4B
24.A10.22B32.4B24.A10.18B$17.A3B22.3A12.B.3B.4B8.4B30.4B22.3A12.B.3B.
4B$16.B2AB23.A19.4B10.4B5.A9.A12.4B23.A19.4B$15.BABA43.4B12.4B4.3A5.
3A11.4B43.4B$14.4B43.4B14.4B6.A3.A13.4B43.4B$13.4B19.A23.4B16.4B4.2A.
B.2A11.4B19.A23.4B$12.4B.3B.B12.3A22.4B18.4B3.7B10.4B.3B.B12.3A22.A3B
$5.18B10.A24.4B20.4B4.3B5.B2AB2A12B10.A24.BABA$4.16B2A2B5.B3.2A11.A
10.4B22.4B2.5B3.2A4BA9B2A2B5.B3.2A11.A10.2B2A$4.16B2A2B3.8B11.3A7.4B
24.4B.6B2.7B2A7B2A2B3.8B11.3A7.4B$4.20B.4B2A2B16.A5.4B20.2A4.11B.A4BA
B2A11B.8B16.A5.4B$4.24B2ABAB15.2A4.4B22.A5.12B2A2BAB2A20B15.2A4.4B$.B
.11B2.2B.8BABAB2AB14.9B6.2A15.A.AB3.12BA2BA4B2.2B.15B14.9B6.2A$2A9B8.
7B2ABA2BA3B14.6B7.A17.2AB2.18B8.17B14.6B7.A$2A7B11.7B2A10B2.2B2.B3.6B
5.2A.A19.19B11.19B2.2B2.B3.6B5.2A.A$.7B12.8B4A3BA11BA7B4.A2.A20.BA16B
12.35B4.A2.A$.7B13.7B.7BA9B2A8B3.B2A21.ABA7BA8B12.7B.12B3A12B3.B2A$3.
4B13.14B3A8BAB3A11B23.2A8B2A6B11.21BA6BA12B$2.4B13.26BABAB2A9B24.3B.
5B2A5B.B2A8.22BABA4BA11B$3.4B13.8B2.16B4A9B30.9B3.BA.A8.8B2.12B2A15B$
3.2B2AB12.6B11.2B.B.5B2A10B30.4B2.4B5.A8.6B11.2B.B.5BABA9B$5.2A14.5B
10.3B4.15B30.3B5.4B4.2A8.5B10.3B4.4BABA8B$21.4B7.2A.2BA5.15B30.2AB6.
4B13.4B7.2A.2BA5.15B$21.4B7.A.2BA.A5.13B30.A.AB7.4B12.4B7.A.2BA.A5.
13B$19.2AB.B9.A2.BA.A2.13B32.2AB9.4B9.2AB.B9.A2.BA.A2.13B$18.A.AB12.A
3.A.A.2A4.8B32.4B8.4B7.A.AB12.A3.A.A.2A4.8B$18.A13.A.4A2.AB2A6.6B34.
2A9.4B6.A13.A.4A2.AB2A6.6B$17.2A12.A.A3.A.A2.B8.5B34.A11.4B4.2A12.A.A
3.A.A2.B8.5B$31.A.A2.A2.2A.2A9.B.B35.3A9.4B17.A.A2.A2.2A.2A9.B.B$32.A
3.2A2.A.A9.3B38.A10.3BA17.A3.2A2.A.A9.3B$40.A.A9.B2AB49.3BA24.A.A9.B
2AB$41.A11.2A51.3A25.A11.2A!
[/code]

p62:
[code]
x = 164, y = 57, rule = LifeHistory
20.2A11.A83.2A$19.B2AB9.A.A82.A.A$20.3B9.A.A2.2A3.A76.A4.2A$19.B.B9.
2A.2A2.A2.A.A71.4A.2A2.A2.A14.2A$19.5B8.B2.A.A3.A.A12.2A57.A2.A.A.A.A
.2A5.A9.A7.A$19.6B6.2ABA2.4A.A13.A60.BABABA.A8.3A7.A.AB2.3A$19.8B4.2A
.A.A3.A12.BA.A61.B2ABA.A11.A7.2AB.A$20.13B2.A.AB2.A9.B.B2A63.2B.BA11.
2A9.2B.A$18.13B5.A.A2B.A7.4B64.3B14.5B6.B2AB$17.15B5.A2B.2A7.4B55.2A
6.4B16.3BAB5.AB$3.2A12.15B4.3B10.5B56.A6.B2A3B13.3BABAB3.2B$3.A.A.2A
7.17B.B.2B11.6B7.2A46.A.AB3.B2A3B12.4BA2BA3B2AB$5.A.2A7.16BABA10B2.8B
8.A14.2A31.2AB.10B11.4B2A3B.2A$2A2.BA9.13B2A7B3A16B7.A.AB11.2A33.13B
11.6B$A2.A.A.2A5.14BABA4B2A2BA15B9.2AB.B.3B40.14B11.5B$.2AB.A.BA4.2AB
3.14B4AB2A6B.7B12.7B3.4A33.15B9.7B$3.A.ABA4.A2.A4.15B3A17B11.7B2.A3.A
35.8B2.4B7.4B.4B$.3A.2A4.A.2A5.6B3.B2.2B2.19B11.7B.2BAB37.6B5.4B5.4B
3.4B$A2.2BA5.A7.6B14.17B8.10BABAB36.9B4.4B3.4B5.4B$2A.2BA4.2A6.9B14.
15B.2B2.13B2A2B35.4B4.2A5.4B.3AB7.4B$2.4B11.4B4.2A15.35B.2A32.4B5.A7.
6BA9.4B13.2A$2.B2AB.B8.4B5.A3.A12.8B.24B4.A31.4B7.3A5.4BA11.4B12.A$2A
2.A2B2A6.4B7.4A10.8B3.2B2A18B6.A.A28.4B10.A4.6B12.4B5.B2.BA.A$.A.2A.B
2A5.4B22.2A3.B5.2B2A17BA7.2A27.4B15.2B2A5B.2A8.4B3.3B.B2A$.A.A3.B5.4B
11.2A11.A10.9BA11BA34.4B15.2B2ABA5B2AB8.4B.6B$2A.A3.2B3.3AB4.A7.A9.3A
12.B.3B.2A2B8.3AB32.4B17.B2ABA2B3.2A10.10B$2.A4.2B2.3BA5.3A2.2A.A7.3A
19.2B2A10.4B30.A3B19.2BA2B5.2A10.5B2A2B2.2A$2A4.7BA9.A.2BA7.A21.4B12.
4B5.A9.A12.B2AB18.5B6.B2AB10.3BA2BA3.A$A4.B3A4B9.A.2B9.2A19.4B14.4B4.
3A5.3A11.BABA19.2A9.BA.A9.4BABAB4.A$.A3.7B10.B3A6.5B18.4B16.4B6.A3.A
13.4B21.A7.2AB.A9.6BAB4.2A$2A2.2A7B10.2B5.5B19.4B18.4B4.2A.B.2A11.4B
4.B14.3A7.A.AB2.3A5.4B2.2B4.A$4.5BA4B10.2B3.7B17.4B20.4B3.7B10.4B.6B
11.3A9.A7.A4.4B3.2B3.A.2A$4.6B.4B8.B2A2B2AB2A4B15.4B22.4B4.3B5.18B10.
A11.2A11.4B5.B3.A.A$2.A2B.2BA3.4B8.2A.2BA2BA3B15.4B24.4B2.BA3B3.16B2A
2B5.B3.2A22.A3B5.3A.2A.A$.A.2A2.A5.4B12.B2A3B4.A10.4B26.4B.ABA3B2.16B
2A2B3.8B10.4A7.BABA6.4AB2.2A$.A12.4B11.5B5.3A7.4B22.2A4.11B.20B.8B12.
A3.A5.2B2A8.B.3AB$2A13.4B9.7B7.A5.4B24.A5.4B3A33B15.2A4.4B11.B2AB$16.
4B7.4B.4B5.2A4.4B25.A.2A3.3B3A14B2.2B.15B14.9B6.2A4.3B.2A$17.4B5.4B3.
4B4.9B27.A2B2.5BA12B8.17B14.6B7.A5.BAB2.A$18.4B3.4B5.4B5.6B30.7B2ABA
8B11.19B2.2B2.B3.6B5.2A.A4.BA.3A$19.4B.4B7.4B2.8B30.A7B2ABA6B12.11B2A
2BABA17B4.A2.A4.2BA.B$20.7B9.15B28.B2A7BA8B12.7B.BA2B2A2BA18B3.B2A4.A
B.A.3A$21.5B11.14B29.2A16B11.10BA2B2A10B2A14B5.2A.A.B2.A$21.6B11.13B
29.3B.12B.B2A8.11BABA2B2A8B2A13B9.2A2.2A$16.2A.3B2A4B11.10B.B2A32.9B
3.BA.A8.8B2.29B7.2A.A$15.A2BA2BA2BA4B12.3B2AB3.BA.A31.4B2.4B5.A8.6B
11.2B.B.17B7.2A.A.A$16.2B3.BABA3B13.3B2AB6.A30.3B5.4B4.2A8.5B10.3B4.
15B12.2A$15.2B5.BA3B16.4B6.2A29.2AB6.4B13.4B7.2A.2BA5.15B$14.A2BA6.5B
14.3B37.A.BA7.4B12.4B7.A.2BA.A5.13B$14.A.2A9.2A11.AB.2B38.ABA9.4B9.2A
B.B9.A2.BA.A2.13B$15.A.3A7.A11.A.AB2AB38.3AB8.4B7.A.AB12.A3.A.A.2A4.
8B$12.3A2.BA.A7.3A8.A.ABABAB39.2A9.4B6.A13.A.4A2.AB2A6.6B$12.A7.A9.A
5.2A.A.A.A.A2.A37.A11.4B4.2A12.A.A3.A.A2.B8.5B$20.2A14.A2.A2.2A.4A38.
3A9.4B17.A.A2.A2.2A.2A9.B.B$38.2A4.A44.A10.3BA17.A3.2A2.A.A9.3B$44.A.
A54.3BA24.A.A9.B2AB$45.2A55.3A25.A11.2A!
[/code]

**Comment by ceebo** [comment]
Thanks
