### ISSUE TITLE
Slightly smaller p492

### ISSUE THREAD

**Issue by ghost** [ceebo/glider_guns#11]
[code]
x = 51, y = 40, rule = LifeHistory
47.A$45.3A$44.A$.A2BA31.2A6.2A$.3BAB30.A.A3.4B$A4BA31.A.5B$2AB.A.AB
30.7B$.B3.AB2A29.4B2A4B.B$6.3B29.4B2A3B.B2A$5.4B3.3B23.11B2A$4.BA2BA
3.4B22.9B.2B$5.2A2.8B.4B11.2B2.10B$9.10B2A4B7.2A13B$9.10B2A5B6.2A13B$
11.15B7.2B.11B$11.6BA9B2.2A5.9B.B2A$10.B2A3BABA8B.B2AB6.7B.BA.A$9.3B
2A2BA2BA7B2.3B5.7B5.A$8.3B2A6BA6B4.B2.2B.8B5.2A$7.4BA2BABA3BA6B.11B2.
4B$7.5B4A5BA4B2.11B3.4B$5.13B3A18B4.4B$5.7B2ABAB3A19B5.4B$4.2B2AB2AB
2A23B.B2A4.4B$4.3B3A24B4.BA.A4.4B$4.4BA3B.20B8.A5.3BA$2.2AB.5B.20B9.
2A5.ABA$.A.AB.4B3.18B18.2A$.A5.3B2.18B$2A5.2B3.17B$12.16B$13.15B5.2A.
2A$13.17B2.B2A.A$14.16B2.3B.A$17.4B.8B.B3A.A.2A$23.4B3.2B3A.A.A$24.3B
4.A.B.2A.A$32.2A3.A$34.3A$34.A!
[/code]

**Comment by ceebo** [comment]
Thanks
