### ISSUE TITLE
Slightly smaller p180 (based on p60)

### ISSUE THREAD

**Issue by ghost** [ceebo/glider_guns#3]
[code]
x = 48, y = 27, rule = LifeHistory
17.3A13.B$4.2A10.3BA11.4B$5.A9.3BA10.3B2AB$3.A7.2B.4B5.2A3.3BA2B2AB$
3.2A6.7B5.A3.B.2B5AB$.2A2.BAB.10B.BA.A2.3B.BAB.2B.2B$A2.4AB4A7B.B2A3.
4B.4A.B2A$2A.A2.5BA9B4.2B4A4.AB2A2B$.A.A.A15B4.BABABA.2A.A.ABA2B$.A.A
.A2B.2A10B3.2BABA.A.2A.ABABAB4.2A$2A.AB.A3.11B4.2B2ABA4.4A2B4.2A$3.A
8.B.8B5.2AB.4A.4B$3.A.A8.9B4.2B.2B.BAB.3B3.4A$4.2A9.3B2.4B5.B5A2B.B4.
A3.A$13.5B3.B3A4.B2A2BA3B7.A.A$13.2A7.A3B5.B2A3B7.3A$14.A8.A3B4.4B8.B
$11.3A10.4B4.B10.B3A$11.A13.8B2.B2A3B.2BA2.A$26.5BA4B2A7B.2A$21.4B2AB
5A6B2A4B$14.B4.5BA4B2A2BA5B3A3B$13.2AB.6BA5B.2B2A5B2A4B$13.2A8BA7BA4B
2A5B$14.9BA7B2.B.B2A3B$14.10BA4B$16.B4.4B2A!
[/code]

**Comment by ceebo** [comment]
Thanks. Added.
